In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
sent=['the glass of juice', 'the cup of tea','I am a good boy', 'I am a good developer']

In [3]:
voc_size=10000

In [6]:
one_hot_repr=[one_hot(words, voc_size) for words in sent]
one_hot_repr

[[4981, 9139, 7082, 1681],
 [4981, 467, 7082, 295],
 [7366, 9527, 9256, 3017, 4612],
 [7366, 9527, 9256, 3017, 2493]]

In [7]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [8]:
import numpy as np

In [10]:
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 4981 9139 7082 1681]
 [   0    0    0    0 4981  467 7082  295]
 [   0    0    0 7366 9527 9256 3017 4612]
 [   0    0    0 7366 9527 9256 3017 2493]]


In [13]:
## feature representation
dim=10
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

d:\Gen_AI\genv\Lib\site-packages\keras\src\layers\core\embedding.py:90: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [16]:
model.summary()

Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_1 (Embedding)         │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [28]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step


array([[[-1.10604055e-02, -1.48882717e-03, -2.72875559e-02,
          3.35702635e-02, -3.41985226e-02,  8.25757906e-03,
         -3.75077240e-02,  6.87051937e-03, -2.80870441e-02,
         -3.20184231e-03],
        [-1.10604055e-02, -1.48882717e-03, -2.72875559e-02,
          3.35702635e-02, -3.41985226e-02,  8.25757906e-03,
         -3.75077240e-02,  6.87051937e-03, -2.80870441e-02,
         -3.20184231e-03],
        [-1.10604055e-02, -1.48882717e-03, -2.72875559e-02,
          3.35702635e-02, -3.41985226e-02,  8.25757906e-03,
         -3.75077240e-02,  6.87051937e-03, -2.80870441e-02,
         -3.20184231e-03],
        [-1.10604055e-02, -1.48882717e-03, -2.72875559e-02,
          3.35702635e-02, -3.41985226e-02,  8.25757906e-03,
         -3.75077240e-02,  6.87051937e-03, -2.80870441e-02,
         -3.20184231e-03],
        [ 4.36301716e-02, -1.03426091e-02,  3.22487466e-02,
         -2.50677224e-02, -2.01079603e-02, -1.98696144e-02,
          2.57361643e-02, -1.23267286e-02,  3.241353

In [24]:
embedded_docs[0]

array([   0,    0,    0,    0, 4981, 9139, 7082, 1681])